services:
  db:
    image: postgres:17-alpine
    container_name: chat-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - .:/app
  app:
    image: golang:alpine
    ports:
      - "${PORT}:${PORT}"
    container_name: chat-app
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "apk add --no-cache make && make run -C /app && ./app/scripts/migrate.sh"
